import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="p-20 bg-blue-400 text-center text-5xl text-bold">
          HELLO
        </h1>
      </div>
    </div>
  );
}
