import Head from 'next/head';
import About from '../components/About';
import Main from '../components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />

      <div className="bg-rose-300/40">
        <About />
      </div>
    </div>
  );
}
