import Head from 'next/head';
import About from '../components/About';
import Main from '../components/Main';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gabriel Dumaug</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />

      <div className="bg-rose-300/40">
        <About />
        <Skills />
        <Projects />
        <Contact />
      </div>
    </div>
  );
}
